export type OutreachMode = "DRAFT" | "APPROVAL_REQUIRED" | "AUTO_SEND";
export type Autonomy = "LOW" | "MEDIUM" | "HIGH";
export type CampaignConfig = {
  name: string;
  objective: string;
  target: string;
  city: string;
  lead_count: number;
  product_ids: string[];
  minimum_score: number;
  outreach_mode: OutreachMode;
  followup_enabled: boolean;
  followup_days: number[];
  handoff_threshold: number;
  autonomy_level: Autonomy;
  provider: "mock" | "csv" | "configured";
  csv_rows?: Record<string, string>[];
  demo_day_seconds: number;
  max_emails: number;
  max_followups: number;
  rate_limit_per_minute: number;
  authorize_auto_send: boolean;
};
export type AgentStatus = {
  agent: string;
  status: "IDLE" | "WORKING" | "WAITING" | "PAUSED" | "ERROR";
  current_task?: string | null;
  last_action?: string | null;
  tasks_completed: number;
  error_count: number;
  next_action?: string | null;
};
export type AgentEvent = {
  id: number;
  campaign_id: number;
  lead_id?: number | null;
  agent: string;
  event_type?: string;
  message: string;
  created_at: string;
  metadata?: Record<string, unknown>;
};
export type AgentTask = {
  id: number;
  campaign_id: number;
  lead_id?: number | null;
  agent: string;
  kind: string;
  status: string;
  due_at: string;
  attempts: number;
  last_error?: string | null;
  result?: { draft_id?: number; [key: string]: unknown };
};
export type CampaignLead = {
  id?: number;
  lead_id: number;
  company_name: string;
  stage: string;
  score?: number | null;
  product_fit?: number | null;
  commercial_potential?: number | null;
  confidence?: number | null;
  qualification?: { product_fit?: number; commercial_potential?: number; confidence?: number; total_score?: number };
  workflow_state?: string;
  workflow_stage?: string;
  current_agent?: string;
  graph?: { step: string; label: string; status: string }[];
  draft_id?: number | null;
  stop_reason?: string | null;
};
export type Campaign = CampaignConfig & {
  id: number;
  name: string;
  status: string;
  created_at: string;
  metrics: Record<string, number>;
  leads?: CampaignLead[];
  agents?: AgentStatus[];
  events?: AgentEvent[];
  tasks?: AgentTask[];
};
export type CloserDetail = {
  id: number;
  lead_id: number;
  company_name: string;
  campaign_id?: number | null;
  campaign_name?: string | null;
  contact_name?: string | null;
  email?: string | null;
  phone?: string | null;
  score?: number | null;
  reason: string;
  summary: string;
  status: string;
  created_at: string;
  owner_name?: string | null;
  compatible_products?: string[];
  last_reply?: string | null;
  objections?: string[];
  extracted?: Record<string, unknown>;
  potential_value?: string | number | null;
  recommended_action?: string | null;
  next_action?: string | null;
  timeline?: { created_at: string; message?: string; reason?: string; agent?: string }[];
};
